[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run db:migrate && npm run start"
healthcheckPath = "/health"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
NODE_VERSION = "18"
